version: '3.4'
services:
    app:
        build: ./php72
        image: app
        container_name: app
        ports:
          - 8080:80
        volumes:
          - ./codeigniter4:/var/www
          - ./codeigniter4/public:/var/www/html